#!/usr/bin/env -S -i /bin/bash

set -e
set -u

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ISMAC=$(test "$(uname -s)" = "Darwin" && echo "1" || echo "")
ISLINUX=$(test "$(uname -s)" = "Linux" && echo "1" || echo "")

# We use `env -i` to disable inheritance of environment variables from
# the developer's own command-line, so that test cases are in control
# over what is and isn't set. But, this means PATH is also cleared.
# Add at least /usr/local, because Docker or Podman may be there.
export PATH="$PATH:/usr/local/bin/"

ENV_IGNORE=("_" "SHLVL" "PWD" "OLDPWD" "PATH")
clean_env() {
	for name in $(compgen -e); do
		if [[ ! " ${ENV_IGNORE[*]} " =~ " ${name} " ]]; then
			# echo "... unset $name"
			unset -v "$name"
		fi
	done
}

cd $BASE

trim() {
	read input
	echo -n "${input%%[[:space:]]}"
}

pushd() {
	# quiet
	command pushd "$1" > /dev/null
}

popd() {
	# quiet
	command popd > /dev/null
}

title() {
	clean_fs
	clean_env

	echo
	echo "test: $1..."
}

if_mac() {
	test -n "$ISMAC" && $1 || echo "      [skip: mac-only]"
}

if_linux() {
	test -n "$ISLINUX" && $1 || echo "      [skip: linux-only]"
}

assert_equals() {
	actual="$1"
	expected="$2"
	if [[ "$actual" == "$expected" ]]; then
		printf "      equals \"$expected\"\n"
	else
		printf "      \"${actual}\" == \"${expected}\"\n"
		false
	fi
}

assert_lastline() {
	assert_equals "$(echo "$1" | tail -n2 | trim)" "$2"
}

assert_contains() {
	printf "      contains \"$2\"\n"
	if [[ "$1" != *"$2"* ]]; then
		printf "\n$1"
		false
	fi
}

assert_matches() {
	printf "      contains \"$2\" (regex)\n"
	if [[ ! "$1" =~ $2 ]]; then
		printf "\n$1"
		false
	fi
}

assert_msg() {
	printf "      $1\n"
}

clean_fs() {
	rm -rf ./fixtures
}
trap clean_fs 0 ERR

title "install / install to ~/.local/bin"
{
	mkdir -p fixtures/install/myhome
	pushd fixtures/install
	myhome="$PWD/myhome"
	mypath="/bin:/usr/bin:$myhome/.local/bin"

	result=$(FRESH_INTERNAL_TEST=1 PATH="$mypath" HOME="$myhome" $BASE/bin/fresh-install)
	assert_matches "$result" "creating .*/myhome/.local/bin"
	assert_contains "$result" "installing fresh-node"
	assert_matches "$result" "Fresh .+ is now ready!"

	result=$(PATH="/bin:/usr/bin:$myhome/.local/bin" fresh-node)
	assert_lastline "$result" "Fake fresh-node"

	popd
}

title "install / install to ~/bin"
{
	mkdir -p fixtures/install/myhome
	pushd fixtures/install
	myhome="$PWD/myhome"
	mypath="/bin:/usr/bin:$myhome/bin"

	result=$(FRESH_INTERNAL_TEST=1 PATH="$mypath" HOME="$myhome" $BASE/bin/fresh-install)
	assert_matches "$result" "creating .*/myhome/bin"
	assert_contains "$result" "installing fresh-node"
	assert_matches "$result" "Fresh .+ is now ready!"

	result=$(PATH="/bin:/usr/bin:$myhome/bin" fresh-node)
	assert_lastline "$result" "Fake fresh-node"

	popd
}

title "install / cannot find a place"
{
	mkdir -p fixtures/install/myhome
	pushd fixtures/install
	myhome="$PWD/myhome"
	mypath="/bin:/usr/bin"
	code=0

	result=$(FRESH_INTERNAL_TEST=1 PATH="$mypath" HOME="$myhome" $BASE/bin/fresh-install 2>&1) || code="$?"
	assert_contains "$result" "Tried the following places: /usr/local/bin, ~/"
	assert_contains "$result" "fresh-install: Could not find writable installation folder"
	assert_equals "$code" "1"

	# must not create any directory or files unless in PATH
	assert_msg "not create ~/bin/" && test ! -e "$myhome/bin"
	assert_msg "not create ~/.local/" && test ! -e "$myhome/.local"

	popd
}

title "basic invocation"
{
	./bin/fresh-node16 -- exit > /dev/null
}

title "runcmd"
{
	result=$(./bin/fresh-node16 -- echo 42)
	assert_lastline "$result" 42

	result=$(./bin/fresh-node16 -- 'echo 42')
	assert_lastline "$result" 42
}

title "forward exit code"
{
	code=0
	./bin/fresh-node16 -- exit 42 > /dev/null || code="$?"
	assert_equals "$code" "42"
}

# This verifies both that the documentation is up-to-date with the
# the current image, and that the current image offers the currently
# documented software and versions thereof.
title "packages / advertised software versions"
{
	result_welcome=$(./bin/fresh-node16 -- exit)
	# There are invisible control characters at the start and end of the output (window title setup),
	# that we need to strip out for the "contains" assertion to work.
	# This is currently done naturally by the output having a line break at the start and end,
	# and grepping only for lines we are intersted in.
	result_live=$(FRESH_INTERNAL_RUNCMD=_fresh_versions ./bin/fresh-node16 | grep --color=never '░')
	assert_contains "$result_welcome" "$result_live"
}

title "environment / default CHROMIUM_FLAGS"
{
	result=$(./bin/fresh-node16 -- 'echo $CHROMIUM_FLAGS')
	assert_lastline "$result" "--no-sandbox"
}

title "environment / warn if no MW_ vars with -env-mw"
{
	mkdir -p fixtures/myproject
	pushd fixtures/myproject

	result=$($BASE/bin/fresh-node16 -env-mw -- exit)
	assert_contains "$result" "env: MW_*, MEDIAWIKI_* (none found)"

	popd
}

title "environment / protect FOO by default"
{
	export FOO="inherited"
	result=$(./bin/fresh-node16 -- 'echo $FOO')
	assert_lastline "$result" ""
}

title "environment / protect MW_FOO by default"
{
	export MW_FOO="inherited"
	result=$(./bin/fresh-node16 -- 'echo $MW_FOO')
	assert_lastline "$result" ""
}

title "environment / inherit MW_FOO with -env"
{
	export MW_FOO="inherited"
	result=$(./bin/fresh-node16 -env -- 'echo $MW_FOO')
	assert_lastline "$result" "inherited"
}

title "environment / inherit MEDIAWIKI_FOO with -env"
{
	export MEDIAWIKI_FOO="inherited"
	result=$(./bin/fresh-node16 -env -- 'echo $MEDIAWIKI_FOO')
	assert_lastline "$result" "inherited"
}

title "environment / inherit MEDIAWIKI_BAR .env file with -env"
{
	mkdir -p fixtures/myproject
	pushd fixtures/myproject
	echo "MEDIAWIKI_BAR=inherited" > .env

	result=$($BASE/bin/fresh-node16 -env -- 'echo $MEDIAWIKI_BAR')
	assert_lastline "$result" "inherited"

	popd
}

title "environment / inherit MEDIAWIKI_BAZ .env file with -env, overriding exported var"
{
	mkdir -p fixtures/myproject
	pushd fixtures/myproject

	export MEDIAWIKI_BAZ="inherited"
	echo "MEDIAWIKI_BAZ=overridden" > .env
	result=$($BASE/bin/fresh-node16 -env -- 'echo $MEDIAWIKI_BAZ')
	assert_lastline "$result" "overridden"

	popd
}

title "environment / warn if no BROWSERSTACK_ vars with -env-bs"
{
	export FOO="inherited"
	result=$($BASE/bin/fresh-node16 -env-bs -- exit)
	assert_contains "$result" "env: BROWSERSTACK_* (none found)"
}

title "environment / inherit BROWSERSTACK vars with -env-bs"
{
	export BROWSERSTACK_KEY="quay"
	result=$($BASE/bin/fresh-node16 -env-bs -- 'echo $BROWSERSTACK_KEY')
	assert_lastline "$result" "quay"
}

title "environment / warn if no SAUCE_ vars with -env-sauce"
{
	export FOO="inherited"
	result=$($BASE/bin/fresh-node16 -env-sauce -- exit)
	assert_contains "$result" "env: SAUCE_* (none found)"
}

title "environment / inherit SAUCE vars with -env-sauce"
{
	export SAUCE_ACCESS_KEY="caye"
	result=$($BASE/bin/fresh-node16 -env-sauce -- 'echo $SAUCE_ACCESS_KEY')
	assert_lastline "$result" "caye"
}

title "environment / protect FOO even with -env-mw"
{
	export FOO="inherited"
	result=$(./bin/fresh-node16 -env-mw -- 'echo $FOO')
	assert_lastline "$result" ""
}

title "environment / inherit FOO with -env=FOO"
{
	export FOO="one"
	export FOOLING="two"
	export BAR="nope"
	export BAR_FOO="nah"
	result=$(./bin/fresh-node16 -env=FOO -- 'echo $FOO $BAR $BAR_FOO $FOOLING')
	assert_lastline "$result" "one two"
}

title "user / default (Linux)"
λ() {
	host_uid=$(id -u)
	result=$(./bin/fresh-node16 -- /usr/bin/id -u)
	assert_lastline "$result" "$host_uid"
}
if_linux λ
# user ID will not be passed on macOS.

title "user / default (macOS)"
λ() {
	result=$(./bin/fresh-node16 -- /usr/bin/id -un)
	assert_lastline "$result" "nobody"
}
if_mac λ

title "user / with -root"
{
	result=$(./bin/fresh-node16 -root -- /usr/bin/id -un)
	assert_lastline "$result" "root"
}

title "mount / expose current directory as readable"
{
	mkdir -p fixtures/myread
	pushd fixtures/myread
	echo "exposed content" > file.txt

	result=$($BASE/bin/fresh-node16 -- cat /myread/file.txt) || true
	assert_lastline "$result" "exposed content"

	popd
}

title "mount / expose current directory as writable"
{
	mkdir -p fixtures/mywrite
	pushd fixtures/mywrite
	echo "original content" > file.txt

	$BASE/bin/fresh-node16 -- 'echo changed content > /mywrite/file.txt' > /dev/null || true
	result=$(cat file.txt)
	assert_lastline "$result" "changed content"

	popd
}

title "mount / cannot write to .git subdirectory file"
{
	mkdir -p fixtures/myproject/.git
	pushd fixtures/myproject
	echo "original content" > .git/file.txt
	code=0

	$BASE/bin/fresh-node16 -- 'echo changed content > /myproject/.git/file.txt' > /dev/null || code="$?"
	result=$(cat .git/file.txt)
	assert_lastline "$result" "original content"
	assert_equals "$code" "2"

	popd
}

title "mount / cannot create a .git subdirectory file"
{
	mkdir -p fixtures/myproject/.git
	pushd fixtures/myproject
	code=0

	$BASE/bin/fresh-node16 -- touch /myproject/.git/file.txt > /dev/null || code="$?"
	result=$(test -f .git/file.txt && echo created file || echo not created)
	assert_equals "$result" "not created"
	assert_equals "$code" "1"

	popd
}
